jobs:
  android-aarch64-gpu0:
    runs-on: ubuntu-latest
    steps:
    - name: cancel-previous-runs
      uses: styfle/cancel-workflow-action@0.9.0
      with:
        access_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v2
      with:
        ref: ${{ matrix.sha }}
        submodules: true
    - name: Setup Python
      run: pip3 install numpy
    - name: Prepare Bazel
      run: ' wget https://x.saltedfish.fun/prepare_bazel.py

        python3 prepare_bazel.py

        '
    - name: Setup Bazel
      run: wget -O .tf_configure.bazelrc https://x.saltedfish.fun/tf_configure.bazelrc
    - name: Build
      run: bash actions_build.sh
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: ${{ matrix.sha }}
        path: bazel-bin/tensorflow/lite/tools
    strategy:
      fail-fast: false
      matrix:
        include:
        - sha: 3ee58683132495864102fb08cd2b1caf56377a93
          time: xxx
        - sha: 59d53b742551314b0a2acd369d9e1ac32053f929
          time: xxx
        - sha: 5f8e3e8d5404ebc6089aa5e83b8342256d0cf4ad
          time: xxx
        - sha: 68b5f1defde0a2f855b2172beb84c5bbed5b1fb3
          time: xxx
        - sha: 20cd718248ceb09a4d770c85af7fd6d4b8fc843f
          time: xxx
        - sha: dd3ce26d7ba4a628cf08902942e5f376808e2052
          time: xxx
name: android-armv8-gpu
'on':
  watch:
    types:
    - started
  workflow_dispatch: null

